# Generated by Django 3.1.4 on 2020-12-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(unique=True, verbose_name='Артикул продавца')),
                ('barcode', models.CharField(max_length=100, verbose_name='Штрих код')),
                ('brand', models.CharField(max_length=250, verbose_name='Бренд товара')),
                ('description', models.CharField(max_length=400, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'Артикли',
            },
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(blank=True, max_length=100, verbose_name='Имя изображения')),
                ('picture', models.ImageField(blank=True, upload_to='image/%Y/', verbose_name='Изображения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main_editor.articledetail', verbose_name='article_image')),
            ],
            options={
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
