# Generated by Django 3.1.4 on 2020-12-24 06:56

from django.db import migrations, models
import django.db.models.deletion
import main_editor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('article', models.IntegerField(primary_key=True, serialize=False, verbose_name='Артикул продавца')),
                ('barcode', models.CharField(max_length=100, verbose_name='Штрих код')),
                ('description', models.CharField(max_length=400, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'Артикли',
                'ordering': ['article'],
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(blank=True, max_length=100, verbose_name='Имя изображения')),
                ('picture', models.ImageField(blank=True, upload_to=main_editor.models.create_path, verbose_name='Изображения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main_editor.articledetail', verbose_name='article_image')),
            ],
            options={
                'verbose_name_plural': 'Изображения',
                'ordering': ['article'],
            },
        ),
        migrations.AddField(
            model_name='articledetail',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='main_editor.brandmodel', verbose_name='article_brand'),
        ),
    ]
